services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/app
    expose:
      - "9000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: u183880556_tcg
      MYSQL_USER: u183880556_tcg_user
      MYSQL_PASSWORD: i98t:4;1*E
      MYSQL_ROOT_PASSWORD: i98t:4;1*E
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/app
    depends_on:
      - app

volumes:
  db_data: {}

